[repository]
name = "phantomat"
authors = ["danihenrique", "kaolti", "yayuuu", "Vaxry"]

[spatialoverview]
description = "Phantomat (danihenrique personal fork): a zoomable, infinite-canvas window manager for Hyprland."
authors = ["danihenrique", "kaolti", "yayuuu", "Vaxry"]
output = "spatialoverview.so"
build = [
    "make all",
]
